Models/ErrorViewModel.cs
namespace SocialNexusClient.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ViewModels/Google/ReportType.cs
namespace SocialNexusClient.ViewModels.Google
{
    public class ReportType
    {
        public string? Id { get; set; }

        public string? name { get; set; }
    }
}

ViewModels/Google/ReportTypeViewModel.cs
namespace SocialNexusClient.ViewModels.Google
{
    public class ReportTypeViewModel
    {
        public string? Id { get; set; }

        public string? name { get; set; }
    }
}

ViewModels/ProductViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SocialNexusClient.ViewModels
{
    public class ProductViewModel
    {
        public int PrimaryKey { get; set; }

        public string? OwnerId { get; set; }

        [StringLength(15)]
        [Required(AllowEmptyStrings = false)]
        public required string Title { get; set; }

        [Required(ErrorMessage = "This field can not be empty.")]
        public required string Description { get; set; }
    }
}

ViewModels/TimeViewModel.cs
namespace SocialNexusClient.ViewModels
{
    public class TimeViewModel
    {
        public required DateTime Now { get; set; }
        public required TimeSpan Formated { get; set; }
    }
}

Controllers/GoogleController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SocialNexusClient.Services;
using SocialNexusClient.ViewModels;

namespace SocialNexusClient.Controllers
{
    public class GoogleController : Controller
    {
        // private IGoogleService _googleService;
        private readonly ILogger<GoogleController> _logger;

        public GoogleController(
            // IGoogleService googleService,
            ILogger<GoogleController> logger
        )
        {
            // _googleService = googleService;
            _logger = logger;
        }

        public IActionResult Index()
        {
            // _logger.LogCritical(objectIdIsNameIdentifier);
            return View();
        }

        // [HttpPost]
        // [Authorize]
        // [ValidateAntiForgeryToken]
        // public async Task<IActionResult> CreateProduct(ProductViewModel p)
        // {
        //     string? objectIdIsNameIdentifier = User.FindFirstValue(ClaimTypes.NameIdentifier);
        //     p.OwnerId = objectIdIsNameIdentifier!;

        //     if (!ModelState.IsValid)
        //         return View("Index");

        //     await _socialNexusService.PostProductAsync(p);
        //     return View("Index");
        // }

        // public async Task<IActionResult> DeleteProduct(int id)
        // {
        //     await _socialNexusService.DeleteProductAsync(id);
        //     return View("Index");
        // }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SocialNexusClient.Models;

namespace SocialNexusClient.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(
            new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier }
        );
    }
}

Controllers/ShopController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SocialNexusClient.Services;
using SocialNexusClient.ViewModels;

namespace SocialNexusClient.Controllers
{
    public class ShopController : Controller
    {
        private ISocialNexusService _socialNexusService;
        private readonly ILogger<ShopController> _logger;

        public ShopController(
            ISocialNexusService socialNexusService,
            ILogger<ShopController> logger
        )
        {
            _socialNexusService = socialNexusService;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateProduct(ProductViewModel p)
        {
            string? objectIdIsNameIdentifier = User.FindFirstValue(ClaimTypes.NameIdentifier);
            p.OwnerId = objectIdIsNameIdentifier!;

            if (!ModelState.IsValid)
                return View("Index");

            await _socialNexusService.PostProductAsync(p);
            return View("Index");
        }

        public async Task<IActionResult> DeleteProduct(int id)
        {
            await _socialNexusService.DeleteProductAsync(id);
            return View("Index");
        }
    }
}

ViewComponents/GoogleViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SocialNexusClient.Controllers;
using SocialNexusClient.Services;
using SocialNexusClient.ViewModels.Google;

namespace SocialNexusClient.ViewComponents
{
    public class GoogleViewComponent : ViewComponent
    {
        private IGoogleService _googleService;
        private readonly ILogger<GoogleViewComponent> _logger;

        public GoogleViewComponent(
            IGoogleService googleService,
            ILogger<GoogleViewComponent> logger
        )
        {
            _googleService = googleService;
            _logger = logger;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            IActionResult res = await _googleService.GetReportTypesAsync();

            if (res is OkObjectResult)
            {
                OkObjectResult ok = (OkObjectResult)res;
                return View(ok.Value!);
            }
            else
            {
                return View("Error");
            }
            // ReportTypeViewModel rt = new ReportTypeViewModel();
            // rt.Id = "channel_annotations_a1";
            // rt.name = "Annotations";
            // List<ReportTypeViewModel> l = new List<ReportTypeViewModel>();
            // l.Add(rt);
        }
    }
}

ViewComponents/ProductsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SocialNexusClient.Controllers;
using SocialNexusClient.Services;

namespace SocialNexusClient.ViewComponents
{
    public class ProductsViewComponent : ViewComponent
    {
        private ISocialNexusService _socialNexusService;
        private readonly ILogger<HomeController> _logger;

        public ProductsViewComponent(
            ISocialNexusService socialNexusService,
            ILogger<HomeController> logger
        )
        {
            _socialNexusService = socialNexusService;
            _logger = logger;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            IActionResult res = await _socialNexusService.GetProductsAsync();

            if (res is OkObjectResult)
            {
                OkObjectResult ok = (OkObjectResult)res;
                return View(ok.Value!);
            }
            else
            {
                return View("Error");
            }
        }
    }
}

ViewComponents/TimeViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SocialNexusClient.Controllers;
using SocialNexusClient.Services;

namespace SocialNexusClient.ViewComponents
{
    public class TimeViewComponent : ViewComponent
    {
        private ISocialNexusService _socialNexusService;
        private readonly ILogger<TimeViewComponent> _logger;

        public TimeViewComponent(
            ISocialNexusService socialNexusService,
            ILogger<TimeViewComponent> logger
        )
        {
            _socialNexusService = socialNexusService;
            _logger = logger;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            IActionResult time = await _socialNexusService.GetTimeAsync();

            if (time is OkObjectResult)
            {
                OkObjectResult res = (OkObjectResult)time;
                return View(res.Value!);
            }
            else
            {
                return View("Error");
            }
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SocialNexusClient</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SocialNexusClient.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">SocialNexusClient</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SocialNexusClient - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Google/Index.cshtml
@{
    ViewData["Title"] = "Google";
}
<p>
    @await Component.InvokeAsync("Google")
</p>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-left">
    <h1 class="display-4">Welcome to SocialNexus</h1>
    <p>SocialNexus is a capstone project created by <a href="https://www.linkedin.com/in/ryan-p-lynch/">Ryan P Lynch</a>. It is underdevelopment and is not a finished product. </p>
    <h2>Mission Statement</h2>
    <p>Empower users by giving them easy access to their data on the interent.</p>

    <div class="row">
        <div class="col-md-4">
            <h2>Current Features</h2>
            <ul>
                <li>Create a local account on Azure B2C</li>
                <li>Register using external identity provider: Google or Facebook</li>
                <li>A demo Shop enables users to create and delete products</li>
            </ul>
        </div>
    </div>

    <h2>
        The Shop
    </h2>
    <a class="nav-link text-dark" asp-area="" asp-controller="Shop" asp-action="Index">Go to Shop</a>
    <p>The shop uses the SocialNexusService to create and store products. It showcases the use of identity tokens and access tokens.</p>
    <p>Identity tokens are used by the frontend to hide certain UI elements from unregistered users.</p>
    <p>Access tokens are used by the backend to check if a user is allowed to access an endpoint.
    They also let us know who is calling the endpoint. We can use this to remember who created a product or to prevent another user from deleting a product not owned by them.</p>
</div>

Views/Shared/Components/Google/Default.cshtml
@model IEnumerable<SocialNexusClient.ViewModels.Google.ReportTypeViewModel>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>List</title>
</head>
<body>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>
</body>
</html>

Views/Shared/Components/Products/Default.cshtml
@model IEnumerable<SocialNexusClient.ViewModels.ProductViewModel>
@using System.Security.Claims;

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>List</title>
</head>
<body>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
            @if (User.Identity?.IsAuthenticated == true && User.FindFirstValue(ClaimTypes.NameIdentifier) == item.OwnerId)
            {
                @Html.ActionLink("Delete", "DeleteProduct", new { id=item.PrimaryKey })
            }
            else {}
            </td>
        </tr>
}
    </tbody>
</table>
</body>
</html>

Views/Shared/Components/Time/Default.cshtml
@model SocialNexusClient.ViewModels.TimeViewModel

<p>
    @Model.Now
</p>

Views/Shared/Products/_Create.cshtml
@model SocialNexusClient.ViewModels.ProductViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Create</title>
    </head>
    <body>
        @if (User.Identity?.IsAuthenticated == true)
        {
            <h4>Create a New Product</h4>
            <hr />
            <div class="row">
                <div class="col-md-4">
                    <form asp-controller="Shop" asp-action="CreateProduct">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Title" class="control-label"></label>
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description" class="control-label"></label>
                            <input asp-for="Description" class="form-control" />
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
        }
        else
        {
            <!-- <a class="nav-link text-dark" asp-area="MicrosoftIdentity" asp-controller="Account" asp-action="SignIn("https://social-nexus.net")">Sign in</a> -->
            <a class="nav-link text-dark" asp-area="MicrosoftIdentity" asp-controller="Account" asp-action="SignIn">Sign in to create new products</a>
        }
    </body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SocialNexus</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SocialNexusClient.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SocialNexus</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shop" asp-action="Index">Shop</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SocialNexusClient - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shop/Index.cshtml
@{
    ViewData["Title"] = "Shop";
}
<p>
    @await Component.InvokeAsync("Time")
    @await Html.PartialAsync("Products/_Create")
    @await Component.InvokeAsync("Products")
</p>